# Use postgres/example user/password credentials
version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: smith/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;Username=postgres;Password=example;Database=auction
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80

    ports:
      - 7001:80
      - 7777:7777
    depends_on:
      - rabbitmq
      - postgres
  search-svc:
    image: smith/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@localhost:27017
      - AuctionServiceUrl=http://auction-svc
    ports:
      - 7002:80
    depends_on:
      - rabbitmq
      - mongodb
  identity-svc:
    image: smith/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;Username=postgres;Password=example;Database=identity
    ports:
      - 5000:80
    depends_on:
      - postgres
  gateway-svc:
    image: smith/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
    ports:
      - 6001:80

  bid-svc:
    image: smith/bid-svc:latest
    build: 
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidConnection=mongodb://root:mongopw@localhost:27017
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777

    ports:
      - 7003:80
    depends_on:
      - rabbitmq
      - mongodb      

  notify-svc:
    image: smith/notify-svc:latest
    build: 
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq

    ports:
      - 7004:80
    depends_on:
      - rabbitmq    

  web-app:
    image: smith/web-app:latest
    build: 
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=somethingreallyreallysecret
      - NEXT_URL=http://web-app
      - API_URL=http://gateway-svc/
      - ID_URL=http://identity-svc
      - NEXT_PUBLIC_NOTIFY_URL=http://gatway-svc/notifications